from termin_nanobind.runtime import preload_sdk_libs

preload_sdk_libs("termin_render")

from termin.render_framework._render_framework_native import (
    RenderPipeline,
    PipelineHandle,
    RenderTargetHandle,
    render_target_new,
    render_target_pool_count,
    render_target_pool_list,
    compile_graph_from_json,
    collect_scene_shader_usages,
    ExecuteContext,
    FrameDebugCapturePass,
    FrameGraphCapture,
    FrameGraphDebuggerCore,
    FrameGraphPresenter,
    FrameGraphResource,
    GraphAliasPass,
    FramePass,
    HDRStats,
    InternalSymbolTiming,
    Rect4i,
    RenderContext,
    RenderEngine,
    RenderTargetContext,
    ResourceSpec,
    TcFrameGraphError,
    TcPass,
    TcPassRef,
    TcScenePipelineTemplate,
    TextureFilter,
    tc_frame_graph_build,
    tc_frame_graph_canonical_resource,
    tc_frame_graph_destroy,
    tc_frame_graph_dump,
    tc_frame_graph_get_alias_groups,
    tc_frame_graph_get_error,
    tc_frame_graph_get_error_message,
    tc_frame_graph_get_schedule,
    tc_frame_graph_schedule_at,
    tc_frame_graph_schedule_count,
    tc_pass_registry_get_all_instance_info,
    tc_pass_registry_get_all_types,
    tc_pass_registry_clear_python,
    tc_pass_registry_has,
    tc_pass_registry_register_python,
    tc_pass_registry_unregister_python,
    tc_pass_registry_type_count,
    tc_pipeline_add_pass,
    tc_pipeline_clear_dirty,
    tc_pipeline_collect_specs,
    tc_pipeline_create,
    tc_pipeline_destroy,
    tc_pipeline_get_name,
    tc_pipeline_get_pass,
    tc_pipeline_get_pass_at,
    tc_pipeline_insert_pass_before,
    tc_pipeline_is_dirty,
    tc_pipeline_mark_dirty,
    tc_pipeline_pass_count,
    tc_pipeline_pool_alive,
    tc_pipeline_registry_count,
    tc_pipeline_registry_get_all_info,
    tc_pipeline_remove_pass,
    tc_pipeline_remove_passes_by_name,
    tc_resources_allocate_dict,
)
from termin.render_framework.frame_graph_view import PipelineFrameGraphView
from termin.render_framework.frame_pass_registry import FramePassRegistry
from termin.render_framework.python_pass import PythonFramePass, deserialize_pass, shutdown_python_passes


def shutdown_render_pipelines() -> None:
    """Destroy all live process-global render pipelines."""
    from tcbase import log

    try:
        pipeline_infos = list(tc_pipeline_registry_get_all_info())
    except Exception as exc:
        log.error(f"[RenderFramework] failed to list render pipelines during shutdown: {exc}")
        return

    for info in pipeline_infos:
        try:
            tc_pipeline_destroy(info["handle"])
        except Exception as exc:
            log.error(f"[RenderFramework] failed to destroy render pipeline during shutdown: {exc}")

__all__ = [
    "RenderPipeline",
    "PipelineHandle",
    "RenderTargetHandle",
    "render_target_new",
    "render_target_pool_count",
    "render_target_pool_list",
    "compile_graph_from_json",
    "collect_scene_shader_usages",
    "ExecuteContext",
    "FrameDebugCapturePass",
    "FrameGraphCapture",
    "FrameGraphDebuggerCore",
    "FrameGraphPresenter",
    "FrameGraphResource",
    "GraphAliasPass",
    "FramePass",
    "HDRStats",
    "InternalSymbolTiming",
    "Rect4i",
    "RenderContext",
    "RenderEngine",
    "RenderTargetContext",
    "ResourceSpec",
    "TcFrameGraphError",
    "TcPass",
    "TcPassRef",
    "TcScenePipelineTemplate",
    "TextureFilter",
    "tc_frame_graph_build",
    "tc_frame_graph_canonical_resource",
    "tc_frame_graph_destroy",
    "tc_frame_graph_dump",
    "tc_frame_graph_get_alias_groups",
    "tc_frame_graph_get_error",
    "tc_frame_graph_get_error_message",
    "tc_frame_graph_get_schedule",
    "tc_frame_graph_schedule_at",
    "tc_frame_graph_schedule_count",
    "tc_pass_registry_get_all_instance_info",
    "tc_pass_registry_get_all_types",
    "tc_pass_registry_clear_python",
    "tc_pass_registry_has",
    "tc_pass_registry_register_python",
    "tc_pass_registry_unregister_python",
    "tc_pass_registry_type_count",
    "tc_pipeline_add_pass",
    "tc_pipeline_clear_dirty",
    "tc_pipeline_collect_specs",
    "tc_pipeline_create",
    "tc_pipeline_destroy",
    "tc_pipeline_get_name",
    "tc_pipeline_get_pass",
    "tc_pipeline_get_pass_at",
    "tc_pipeline_insert_pass_before",
    "tc_pipeline_is_dirty",
    "tc_pipeline_mark_dirty",
    "tc_pipeline_pass_count",
    "tc_pipeline_pool_alive",
    "tc_pipeline_registry_count",
    "tc_pipeline_registry_get_all_info",
    "tc_pipeline_remove_pass",
    "tc_pipeline_remove_passes_by_name",
    "tc_resources_allocate_dict",
    "PipelineFrameGraphView",
    "FramePassRegistry",
    "PythonFramePass",
    "deserialize_pass",
    "shutdown_python_passes",
    "shutdown_render_pipelines",
]
